### ISSUE TITLE
Pass state around instead of using a gen_server

### ISSUE THREAD

**Issue by devinus** [saponinsky/erl-scrypt#1]
It would be better to initialize a state and pass that around instead of using a gen_server for all scrypt calls. You can overload the mailbox if your app makes a lot of calls to the scrypt_worker.

E.g.:

``` erlang
State = scrypt:init(Options),
{ok, Hash} = scrypt:hash(Pass, State),
true = scrypt:verify(Hash, Pass, State).
```

**Comment by saponinsky** [comment]
Definitely true. I was actually thinking of doing some form of resource management, but then realised that I had to understand exactly the performance characteristics of scrypt to do so properly, and decided to pass on that option.

I've written some new code that is just a straightforward passthrough to the NIF functions instead.
